# Generated by Django 2.2.5 on 2019-09-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexusbase_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='data',
            new_name='attributes',
        ),
        migrations.RemoveField(
            model_name='card',
            name='title',
        ),
    ]
