# Generated by Django 2.2.5 on 2019-09-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexusbase_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='fields',
            new_name='attributes',
        ),
    ]
